### ISSUE TITLE
NPE on TensorFlowFeatureBuilder within Scio

### ISSUE THREAD

**Issue by richwhitjr** [spotify/featran#110]
If scio is upgraded to the current version of featran and the tf tests are run `sbt "project scio-tensorflow" test` you see the following error

```
[info] FeatureSpecJob
[info] - should work *** FAILED ***
[info]   org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.NullPointerException
[info]   at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:342)
[info]   at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:312)
[info]   at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:206)
[info]   at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:62)
[info]   at org.apache.beam.sdk.Pipeline.run(Pipeline.java:311)
[info]   at org.apache.beam.sdk.testing.TestPipeline.run(TestPipeline.java:353)
[info]   at org.apache.beam.sdk.testing.TestPipeline.run(TestPipeline.java:335)
[info]   at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:369)
[info]   at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:354)
[info]   at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:419)
[info]   ...
[info]   Cause: java.lang.NullPointerException:
[info]   at com.spotify.featran.tensorflow.package$TensorFlowFeatureBuilder.init(package.scala:28)
[info]   at com.spotify.featran.CrossingFeatureBuilder.init(CrossingFeatureBuilder.scala:90)
[info]   at com.spotify.featran.FeatureSet.featureValues(FeatureSpec.scala:300)
[info]   at com.spotify.featran.FeatureExtractor.$anonfun$featureResults$1(FeatureExtractor.scala:96)
[info]   at com.spotify.scio.util.Functions$$anon$7.processElement(Functions.scala:145)
[info]   ...
[info] MultiSpecJob
[info] - should work *** FAILED ***
[info]   org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.NullPointerException
[info]   at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:342)
[info]   at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:312)
[info]   at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:206)
[info]   at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:62)
[info]   at org.apache.beam.sdk.Pipeline.run(Pipeline.java:311)
[info]   at org.apache.beam.sdk.testing.TestPipeline.run(TestPipeline.java:353)
[info]   at org.apache.beam.sdk.testing.TestPipeline.run(TestPipeline.java:335)
[info]   at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:369)
[info]   at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:354)
[info]   at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:419)
[info]   ...
[info]   Cause: java.lang.NullPointerException:
[info]   at com.spotify.featran.tensorflow.package$TensorFlowFeatureBuilder.init(package.scala:28)
[info]   at com.spotify.featran.CrossingFeatureBuilder.init(CrossingFeatureBuilder.scala:90)
[info]   at com.spotify.featran.MultiFeatureSet.multiFeatureValues(FeatureSpec.scala:417)
[info]   at com.spotify.featran.MultiFeatureExtractor.$anonfun$featureResults$1(MultiFeatureExtractor.scala:73)
[info]   at com.spotify.scio.util.Functions$$anon$7.processElement(Functions.scala:145)
[info]   ...
```

Best current guess is that something is causing the underlying Features.Builder to get created and then needs serialization which doesn't happen because of the transient annotation.

**Comment by richwhitjr** [comment]
Confirmed that this fails on an internal job also, not just in the unit test.

**Comment by richwhitjr** [comment]
Looks like tensorflow is a small blind spot in the unit tests.  Because we don't want to introduce the TF dependency to each data tool we don't explicitly test the serialization of tensorflow builders.
