### ISSUE TITLE
IndexOutOfBoundsException when using HashOneHotEncoder with SparseVector

### ISSUE THREAD

**Issue by nevillelyh** [spotify/featran#31]
Not sure if user or featran code bug but here's the partial stacktrace:

```
Caused by: java.lang.IndexOutOfBoundsException: 8239914 not in [0,8239912)
	at breeze.linalg.VectorBuilder.breeze$linalg$VectorBuilder$$boundsCheck(VectorBuilder.scala:92)
	at breeze.linalg.VectorBuilder.add(VectorBuilder.scala:112)
	at breeze.linalg.SparseVector$$anonfun$apply$2.apply(SparseVector.scala:196)
	at breeze.linalg.SparseVector$$anonfun$apply$2.apply(SparseVector.scala:195)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:73)
	at scala.collection.mutable.MutableList.foreach(MutableList.scala:30)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at breeze.linalg.SparseVector$.apply(SparseVector.scala:195)
	at com.spotify.featran.FeatureBuilder$$anon$5.result(FeatureBuilder.scala:134)
	at com.spotify.featran.FeatureBuilder$$anon$5.result(FeatureBuilder.scala:117)
	at com.spotify.featran.FeatureExtractor$$anonfun$featureValuesWithOriginal$1.apply(FeatureExtractor.scala:96)
	at com.spotify.featran.FeatureExtractor$$anonfun$featureValuesWithOriginal$1.apply(FeatureExtractor.scala:94)
	at com.spotify.scio.util.Functions$$anon$7.processElement(Functions.scala:145)
```

**Comment by fallonchen** [comment]
This case can be reproduced when HashOneHotEncoder (using the defaults for hashBucketSize and sizeScalingFactor) comes before OneHotEncoder in the FeatureSpec. Since OneHotEncoder doesn't call fb.init(), the length set for SparseVector stays the same as it does from HashOneHotEncoder (i.e. smaller than expected due to collisions), which causes the OOB exception to be thrown by VectorBuilder. I think it's possible that other encoders that override buildFeatures without calling fb.init() first could also cause this bug. 

Suggested fix: add fb.init() to overridden buildFeature methods where needed.

**Comment by nevillelyh** [comment]
Actually `fb.init` should be called once per record i.e. in https://github.com/spotify/featran/blob/master/core/src/main/scala/com/spotify/featran/FeatureSpec.scala#L283 where `featureDimension(c) ` is the size of all transformers summed up and not individual ones. So we should remove `fb.init(c)` in `Hash*Encoder`s.
