### ISSUE TITLE
UnsupportedOperationException when using TensorFlowFeatureBuilder

### ISSUE THREAD

**Issue by martinbomio** [spotify/featran#64]
Getting the following error when using `TensorFlowFeatureBuilder` to build `Example` with `fe.featureValues[Example]`:
```
java.lang.UnsupportedOperationException
    at com.google.protobuf.MapField.ensureMutable(MapField.java:290)
    at com.google.protobuf.MapField$MutatabilityAwareMap.put(MapField.java:333)
    at org.tensorflow.example.Features$Builder.putFeature(Features.java:631)
    at com.spotify.featran.tensorflow.package$TensorFlowFeatureBuilder$.add(package.scala:30)
    at com.spotify.featran.CrossingFeatureBuilder.add(CrossingFeatureBuilder.scala:96)
    at com.spotify.featran.transformers.StandardScaler.buildFeatures(StandardScaler.scala:55)
    at com.spotify.featran.transformers.StandardScaler.buildFeatures(StandardScaler.scala:42)
    at com.spotify.featran.transformers.Transformer.optBuildFeatures(Transformer.scala:83)
    at com.spotify.featran.Feature.unsafeBuildFeatures(FeatureSpec.scala:148)
    at com.spotify.featran.FeatureSet.featureValues(FeatureSpec.scala:270)
    at com.spotify.featran.FeatureExtractor$$anonfun$featureResults$1.apply(FeatureExtractor.scala:94)
    at com.spotify.featran.FeatureExtractor$$anonfun$featureResults$1.apply(FeatureExtractor.scala:93)
    at com.spotify.scio.util.Functions$$anon$7.processElement(Functions.scala:145)
```
Spec:

```scala
    FeatureSpec
      .of[Features]
      .required(_.doubleFeature)(StandardScaler("reg_feature", withMean = true, withStd = true))
```
Using featran `0.1.11` and scio `0.4.3` and  `protobuf-java;3.3.1`

**Comment by annaks** [comment]
Fixed in https://github.com/spotify/featran/pull/65

**Comment by annaks** [comment]
@martinbomio can you confirm?

**Comment by martinbomio** [comment]
@annaks seems like the fix worked!
